-- ============================================================================
-- SECURITY: RLS Policy for Payment Link Fields
-- Date: 2026-02-03
-- Purpose: Restrict payment_link_url and payment_link_sent_at updates to ADMIN only
-- ============================================================================

-- Context: Payment links are manually generated by the admin team and sent
-- via email/WhatsApp. Clients and suppliers should NOT be able to update
-- these fields to prevent phishing attacks where they point to malicious URLs.

-- ============================================================================
-- Add columns to orders table (if not already added)
-- ============================================================================
DO $$ 
BEGIN
  -- Add payment_link_url if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'orders' 
    AND column_name = 'payment_link_url'
  ) THEN
    ALTER TABLE public.orders ADD COLUMN payment_link_url TEXT NULL;
  END IF;

  -- Add payment_link_sent_at if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'orders' 
    AND column_name = 'payment_link_sent_at'
  ) THEN
    ALTER TABLE public.orders ADD COLUMN payment_link_sent_at TIMESTAMPTZ NULL;
  END IF;
END $$;

-- ============================================================================
-- RLS Policy: Only admins can update payment link fields
-- ============================================================================

-- Drop any existing conflicting policies first
DROP POLICY IF EXISTS "Admins can update payment links" ON public.orders;
DROP POLICY IF EXISTS "Only admins can set payment links" ON public.orders;

-- Create a policy that allows admins to update any order
-- This is simpler and covers payment link updates
CREATE POLICY "Admins can update all order fields" ON public.orders
  FOR UPDATE
  TO authenticated
  USING (
    -- Only admins can update orders
    (SELECT role FROM public.users WHERE id = auth.uid()) = 'ADMIN'
  );

-- Ensure clients and suppliers can still view their own orders
-- (This should already exist, but adding for completeness)
DROP POLICY IF EXISTS "Users can view their own orders" ON public.orders;
CREATE POLICY "Users can view their own orders" ON public.orders
  FOR SELECT
  TO authenticated
  USING (
    auth.uid() = client_id 
    OR auth.uid() = supplier_id 
    OR (SELECT role FROM public.users WHERE id = auth.uid()) = 'ADMIN'
  );

-- ============================================================================
-- Add helpful comment
-- ============================================================================
COMMENT ON COLUMN public.orders.payment_link_url IS 
  'External payment link manually generated by admin team. Only admins can update.';

COMMENT ON COLUMN public.orders.payment_link_sent_at IS 
  'Timestamp when payment link was sent to client via email/WhatsApp. Only admins can update.';

-- ============================================================================
-- Verification
-- ============================================================================
DO $$
BEGIN
  RAISE NOTICE 'SECURITY: Payment link RLS policy created';
  RAISE NOTICE 'Only ADMIN role can update payment_link_url and payment_link_sent_at';
  RAISE NOTICE 'Clients and suppliers can view but not modify these fields';
END $$;
